***Variables***
${dressProduct}     http://automationpractice.com/index.php?id_product=4&controller=product#/size-s/color-pink
${addToCartButton}  css:button.exclusive
${continueShoppingButton}   css:span[title="Continue shopping"]
${proceedCheckoutButton}    css:a[title="Proceed to checkout"]
${closePopup}               css:span.cross
${viewShoppingCart}         css:[title="View my shopping cart"]
${cartProduct}                css:[title="Printed Dress"]